### PR TITLE
avoid side effects (mutating global text)

### PR DESCRIPTION
**Pull request by nicholaswmin**
- Avoid mutating global text inside iterations within the `createMarkdown` func.

It's a bit longer as a function - maybe i'm not [KISS][1] 👯‍♂️  - Worth the try.

Assuming `categories` is something like:

```javascript
const categories = [
  {
    title: "Foo",
    data: [
      {
        title: "Title Foo 1",
        statement: "Statement Foo 1",
        banner: "Banner Foo 1",
        description: "Description Foo 1"
      },
      {
        title: "Title Foo 2",
        statement: "Statement Foo 2",
        banner: "Banner Foo 2",
        description: "Description Foo 2"
      }
    ]
  },
  {
    title: "Bar",
    data: [
      {
        title: "Title Bar 1",
        statement: "Statement Bar 1",
        banner: "Banner Bar 1",
        description: "Description Bar 1"
      },
      {
        title: "Title Bar 2",
        statement: "Statement Bar 2",
        banner: "Banner Bar 2",
        description: "Description Bar 2"
      }
    ]
  }
]
```

[1]: https://en.wikipedia.org/wiki/KISS_principle

### CODE REVIEW

**Comment by stefanoschrs** [comment]
@nicholaswmin Can you elaborate on the *Side Effects* ?

**Comment by nicholaswmin** [comment]
> In computer science, a function or expression is said to have a side effect if it modifies some state  outside its scope. 

Mostly mentioned when discussing [Functional Javascript][1] stuff

i.e

```javascript
// this statement has a side effect. It mutates something outside of it's 
// scope, in this case `text`
let text = "";

// `text` is not part of the following statement.
["foo", "bar"].forEach((item) => text += item);

// This statement does not have a side effect. The variable it mutates (`text`) is part 
// of the statement
text = ["foo", "bar"].reduce((text, item) => text += item, "");
```


[1]: http://eloquentjavascript.net/1st_edition/chapter6.html

**Comment by stefanoschrs** [comment]
Interesting!

**Comment by nicholaswmin** [comment]
Indeed - I don't think it adds anything though, since text is scoped in `createMarkdown()` anyway and to be frank the consecutive `forEach` reads more nicely.

I just wanted to issue a PR 😄

**Pull request closed without merging**
